version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      - 'POSTGRES_HOST=172.25.0.2'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_DB=test'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
    networks:
      net:
        ipv4_address: 172.25.0.2

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
